"use strict";
require("dotenv").config();
let email = require("./src/mailer");

class emailController {
  async sendEmail(req, res) {
    let emailPtr = new email();
    await emailPtr.sendMail(req.body, res).then(()=> {
      return res.json({
        icon:'success',
        title:'Successfully Dispatched',
        message:'An autogenerated email for the selected agent/s have been dispatched.',
      });
    });
  }
}

module.exports = new emailController();
